api: /assets/js/api.js
author-avatar: https://avatars.githubusercontent.com/u/25187397?s=400&u=7c5cc8d7030f8d04105f7936c329030b0c3cc768&v=4
author-github: https://github.com/alanmatzumiya
author-name: Alan Matzumiya
author-website: https://alanmatzumiya.github.io
baseurl: ''
css: /assets/css
description: From Here To Eternity
disqus-identifier: alan-matzumiya
facebook: https://www.facebook.com/circuitalminds
fb_id: 772020893629559
github: https://github.com/CircuitalMinds
google-analytics: UA-177619690-2
header_pages:
- projects
- topics
- contact
- about
img: /assets/img
include:
- _pages
- _applications
instafeed: false
instagram: https://www.instagram.com/circuitalminds
js: /assets/js
libs:
  apexcharts:
    js: apexcharts/dist/apexcharts.js
  metro:
    css: metro/css/metro-all.css
    js: metro/js/metro.js
logo: https://avatars.githubusercontent.com/u/75770878?s=400&u=85be0810ccfb5f56a393f71cf971021f087c5a59&v=4
mailchimp: null
markdown: kramdown
paginate: 7
paginate_path: /page/:num
permalink: :title/
pinterest: https://www.pinterest.com/circuitalminds
plugins:
- jekyll-paginate
- jekyll-sitemap
sass:
  sass_dir: _sass
  style: compressed
scripts:
  after:
  - utils.js
  - pages.js
  - posts.js
  before:
  - instafeed.min.js
  - facebook.js
  - jquery.waitforimages.min.js
  - jquery.fitvids.js
  - common.js
static:
  apps: https://circuitalminds.github.io/static/apps
  css: https://circuitalminds.github.io/static/css
  data: https://circuitalminds.github.io/static/data
  docs: https://circuitalminds.github.io/static/docs
  img: https://circuitalminds.github.io/static/img
  js: https://circuitalminds.github.io/static/js
  libs: https://circuitalminds.github.io/static/libs
  storage: https://circuitalminds.github.io/static/storage
styles:
- main.css
- actions.css
- modal.css
- dropdown.css
templates: https://circuitalminds.github.io/templates
title: Circuital | Minds
twitter: https://twitter.com/circuitalminds
url: https://circuitalminds.github.io
