#-------------------------------
# General Site Settings

title: Circuital | Mynds
description: Official Website # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://circuitalminds.github.io" # the base hostname & protocol for your site, e.g. http://example.com


#-------------------------------
# About Section
author-name:   Alan Matzumiya
author-avatar: avatar.jpg


#-------------------------------
# Contact links
facebook:  https://www.facebook.com/CircuitalMinds/ # Add your Facebook handle
twitter:   https://twitter.com/ # Add your Facebook handle
instagram: https://www.instagram.com/alanmatzumiya # Add your Facebook handle
pinterest: https://www.pinterest.com/alanmatzumiya # Add your Facebook handle


#-------------------------------
# Comment Section (Disqus)
disqus-identifier: alan-matzumiya # Add your shortname for Disqus Comment. For example mr-brown


#-------------------------------
# Instagram Feed
instafeed: false # To enable the instafeed, use the value true. To turn off use the value false.


#-------------------------------
# Google Analytics
google-analytics: UA-177619690-2 # Add your identifier. For example UA-99631805-1.


#-------------------------------
# Newsletter
mailchimp: # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e


#-------------------------------
# Build settings
markdown: kramdown
permalink: ':title/'
plugins:
  - jekyll-paginate
  - jekyll-sitemap

paginate: 7
paginate_path: "/page/:num"

include:
  - _pages

sass:
  sass_dir: _sass
  style: compressed


js: "/static/js/blog"
css: "/static/css/blog"
img: "/static/images/blog" 

picsdemo:
  - 01.jpg
  - 02.jpg
  - 03.jpg
  - 04.jpg
  - 05.jpg
  - 06.jpg
  - 07.jpg
  - 08.jpg
  - 09.jpg
  - 10.jpg
  - 11.jpg

#-------------------------------
# Exclude from processing.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
