#-------------------------------
# General Site Settings
title: Circuital | Minds
title_page: CircuitalMinds
description: Spinning out gracefully # this means to ignore newlines until "baseurl:"
logo: images/circuitalminds.jpg
#-------------------------------
# proprietary info
author-name: Alan Matzumiya
author-avatar: images/avatar.jpg
author-website: "https://alanmatzumiya.github.io"
#-------------------------------
# Open Graph
fb_id: 772020893629559
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://circuitalminds.github.io" # the base hostname & protocol for your site, e.g. http://example.com
#-------------------------------
# Contact links
facebook:  https://www.facebook.com/CircuitalMinds/ # Add your Facebook handle
twitter:   https://twitter.com/ # Add your Facebook handle
instagram: https://www.instagram.com/alanmatzumiya # Add your Facebook handle
pinterest: https://www.pinterest.com/alanmatzumiya # Add your Facebook handle
#-------------------------------
# static-folders
static:
  js: "static/js"
  css: "static/css"  
  images: "static/images"
  data: "static/data"
#-------------------------------
# templates-folders
templates:
  applications: "templates/applications"
  views: "templates/views"
#-------------------------------
# manager-resource
Api: "/Api.js"
#-------------------------------
# external-resources 
libs:
  jquery: "https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"
  
scripts:
  - jekyll_search:
    src: "js/simple-jekyll-search.min.js"
  - setup_instagram:
    src: "js/instafeed.min.js"
  - waitforimages:
    src: "js/jquery.waitforimages.min.js"
  - fitvids:
    src: "js/jquery.fitvids.js"
  - common:
    src: "js/common.js"
  - utils:
    src: "js/utils.js"
styles:
  - utils:
    href: "css/utils.css"
   
#-------------------------------
# Comment Section (Disqus)
disqus-identifier: alan-matzumiya # Add your shortname for Disqus Comment. For example mr-brown
#-------------------------------
# Instagram Feed
instafeed: false # To enable the instafeed, use the value true. To turn off use the value false.
#-------------------------------
# Google Analytics
google-analytics: UA-177619690-2 # Add your identifier. For example UA-99631805-1.
#-------------------------------
# Newsletter
mailchimp: # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e
#-------------------------------
# Build settings
markdown: kramdown
permalink: ':title/'
plugins:
  - jekyll-paginate
  - jekyll-sitemap
paginate: 7
paginate_path: "/page/:num"
include:
  - _pages
sass:
  sass_dir: _sass
  style: compressed

server: http://192.168.50.7:8000
previews: https://circuitalminds.github.io/previews/blog
js: https://circuitalminds.github.io/static/js/blog
css: https://circuitalminds.github.io/static/css/blog
img: https://circuitalminds.github.io/static/images/blog
view_apps:  
  - app: 
    id: 'desktop'
    caption: 'Desktop App'
    image: 'desktop.jpg'
  - app:
    id: 'music_app'
    caption: 'Music App'
    image: 'music_app.jpg'
  - app:
    id: 'chat_app'
    caption: 'Chat App'
    image: 'chat_app.jpg'
  - app:    
    id: 'inbox_app'
    caption: 'Inbox App'
    image: 'inbox_app.jpg'
  - app:
    id: 'console_app'
    caption: 'Console App'
    image: 'console_app.jpg'
    
metadata:
  - meta:
    name: author
    content: alanmatzumiya
  - meta:
    name: description
    content: Spinning out gracefully
  - meta:
    name: robots
    content: index, follow
  - meta:
    name: viewport
    content: "width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no"
open_graph:
  - meta:
    property: fb:app_id
    content: 772020893629559
  - meta:
    property: "og:description"
    content: Spinning out gracefully
  - meta:
    property: "og:image"
    content: images/logo.jpg
  - meta:
    property: "og:site_name" 
    content: CircuitalMinds
  - meta:
    property: "og:title"
    content: CircuitalMinds
  - meta:
    property: "og:type"
    content: website
  - meta:
    property: "og:url"
    content: "https://circuitalminds.github.io"
  
#-------------------------------
# Exclude from processing.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
