#-------------------------------
# General Site Settings
#-------------------------------

baseurl: ""
url: "http://192.168.50.100"
title: "CircuitalMinds"
description: "From Here To Eternity."
logo: "https://avatars.githubusercontent.com/u/75770878?s=400&u=85be0810ccfb5f56a393f71cf971021f087c5a59&v=4"

#-------------------------------
# Contact links
#-------------------------------

facebook: "https://www.facebook.com/circuitalminds"
twitter: "https://twitter.com/circuitalminds"
instagram: "https://www.instagram.com/circuitalminds"
pinterest: "https://www.pinterest.com/circuitalminds"
github: "https://github.com/CircuitalMinds"

disqus-identifier: "alan-matzumiya"
instafeed: "false"
google-analytics: "UA-177619690-2"
mailchimp: # Add your MailChimp form identifier.

#-------------------------------
# Directory
#-------------------------------

js: "assets/js"
css: "assets/css"
img: "assets/img"
static_url: "https://circuitalminds.github.io/static"

scripts: [
  "instafeed.min",
  "facebook",
  "jquery.waitforimages.min",
  "jquery.fitvids",
  "common",
  "simple-jekyll-search.min"
]

styles: [
  "logo",
  "helpers",
  "modal",
  "sizes",
  "gradient",
  "chat"
]

module:
  datetime: "module/element/datetime.html"
  image-sticky: "module/element/image-sticky.html"
  accordion: "module/element/accordion.html"
  slider: "module/element/slider.html"
  code-style: "module/element/code-style.html"
  animation: "module/element/animation"

#-------------------------------
# Build settings
#-------------------------------

home-pages:
  - {name: "vahngraff", url: "/app/vahngraff/"}
  - {name: "topics", url: "/topics/"}
  - {name: "contact", url: "/contact/"}  
  - {name: "about", url: "/about/"}

markdown: "kramdown"
permalink: ":title/"
plugins:
  - "jekyll-paginate"
  - "jekyll-sitemap"

paginate: "7"
paginate_path: "/page/:num"
include:
  - "_pages"

sass:
  sass_dir: "_sass"
  style: "compressed"

#-------------------------------
# Exclude from processing.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
#-------------------------------