#!/bin/bash


allow_push=true
user=alanmatzumiya
repo=CircuitalMinds/circuitalminds.github.io.git

if $allow_push; then 

    git add .
    git commit -m "autocommit"
    git push https://$user:"$( head "$HOME"/secret )"@github.com/$repo  

fi
