main: app/templates/main.html
index: app/index.html
chat: app/chat.html

template:
  header:
    html: app/templates/header.html
    buttons-top: [
      {
        url: "#mail",
        icon: "envelope"
      },
      {
        url: "#user",
        icon: "user"
      },
      {
        url: "#settings",
        icon: "cog"
      }
    ]
    buttons-down: [
      {
        url: "#news",
        icon: "bell",
        text: "News"
      },
      {
        url: "#general",
        icon: "bank",
        text: "General"
      },
      {
        url: "history",
        icon: "history",
        text: "History"
      },
      {
        url: "#settings",
        icon: "cog",
        text: "Settings"
      }
    ]
    links: [
      {
        text: Log-In,
        url: /login/
      }
    ]
  video:
    html: app/templates/video.html
    buttons: [
        play,
        pause,
        previous,
        next,
        volume-minus,
        volume-plus
    ]
    poster: poster.gif
  panel:
    html: app/templates/panel.html

folder-icon: icon mif-folder fg-cyan
file-icon": icon mif-file-empty fg-teal

styles: [
  app/styles/utils.css,
  app/styles/index.css
]

jupyter:
  url-content: https://raw.githubusercontent.com/CircuitalMinds/jupyter
  url-root: https://jupyternbs.herokuapp.com/notebooks

